### ISSUE TITLE
0.2.5

### ISSUE THREAD

**Issue by antondemanov** [IAkumaI/SphinxsearchBundle#12]
Hello! Please create new tag 0.2.5 (8 new commits since 0.2.4 contain some important changes)

**Comment by Blackskyliner** [comment]
@IAkumaI any plans when the new version will hit? Maybe after #13 gets merged in? Its a bit bothersome to currently only have this bundle as 'dev-master' dependency within a project...

**Comment by antondemanov** [comment]
No more need this bundle, I've switched to SphinxQl instead. It's much nicer to write just sql.
