### ISSUE TITLE
Index order in searchEx();

### ISSUE THREAD

**Issue by rifats** [IAkumaI/SphinxsearchBundle#8]
Здравствуйте.
Разрешите, еще позанудствовать.
При использовании метода searchEx() результат зависит от очередности индексов в массиве.
Пробовал три - searchEx($request->query->get('q', ''), array('Index1', 'Index2', 'Index3'));
Если первым указать 'Index3', то результат существенно изменяется.
Меняется даже значение total_found.
Это нормально?

**Comment by IAkumaI** [comment]
Честно, не замечал. Возможно по умолчанию веса индексов зависят от очередности.
Попробуйте метод `$sphinxSearch->SetIndexWeights()` для установки "весов" индексов.
