### ISSUE TITLE
Use of deprecated features

### ISSUE THREAD

**Issue by todpetkov** [IAkumaI/SphinxsearchBundle#9]
Using latest stable Symfony 2.7.7 with SphinxsearchBundle integrated. Symfony throws the following messages for deprecated features:

DEPRECATED - The Twig_Filter_Function class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFilter instead. +
DEPRECATED - The Twig_Filter class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFilter instead. +
DEPRECATED - Using an instance of "Twig_Filter_Function" for filter "sphinx_highlight" is deprecated. Use Twig_SimpleFilter instead.

**Comment by qbbr** [comment]
pull request #10

**Comment by qbbr** [comment]
bump
